#!/usr/bin/env zsh

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --adopt --target $HOME -D $folder
    stow --adopt --target $HOME $folder
    git restore .
done
popd
