#!/usr/bin/env zsh

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="zsh,scripts,git,alacritty,p10k"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Developer/unkrich/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
