#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="zsh,nvim,tmux,scripts,git,yabai,skhd,sketchybar,hammerspoon,alacritty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Developer/unkrich/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
